FROM ubuntu
RUN \
    apt-get -y update && \
    apt-get -y install apt-utils && \
    apt-get -y install git && \
    apt-get -y install python3 && \
    apt-get -y install python3-pip && \
    python3 -m pip install signalfx_tracing flask && \
    export PATH="$HOME/.local/bin:$PATH" && sfx-py-trace-bootstrap && \
    cd /usr/src && \
    git clone https://github.com/stevelsplunk/signalfx
EXPOSE 5000
