FROM python:3
RUN apt-get update
RUN apt install -y apt-utils
RUN mkdir /home/code
RUN git clone https://github.com/slernersplunk/signalfx /home/code
RUN apt -y autoremove && apt-get -y autoclean
RUN cd /home/code/apm/apm-python/flask && \
python3 -m pip install signalfx_tracing flask && \
export PATH="$HOME/.local/bin:$PATH" && \
sfx-py-trace-bootstrap && \
python3 flask-server.py 
